import {api,app,can,empty,esc,fmtDate,loading,renderError,setMeta} from './core.js';
const labels={pending:['待支付','gold'],paid:['已支付','green'],closed:['已关闭',''],failed:['失败','red'],refunded:['已退款','']};
const money=fen=>`¥${((Number(fen)||0)/100).toFixed(2)}`;
let currentStatus='';
export async function renderPaymentOrders(){
 setMeta('payment-orders');if(!can('user.manage')){app.innerHTML=`<div class="card">${empty('无权限','仅管理员可以查询支付订单')}</div>`;return}loading('正在读取支付订单…');
 try{paint(await api(`/api/billing/orders?status=${encodeURIComponent(currentStatus)}&limit=200`),currentStatus)}catch(e){renderError(e)}
}
function paint(data,status){const items=data.items||[],paid=items.filter(x=>x.status==='paid');app.innerHTML=`<div class="page-intro"><div><h2>支付订单</h2><p>微信支付订单、到账状态和交易号只读查询</p></div></div><div class="quota-summary-grid"><article class="quota-summary-card"><div><span>当前列表</span><strong>${items.length}</strong></div><p>按创建时间倒序</p></article><article class="quota-summary-card paid"><div><span>已支付</span><strong>${paid.length}</strong></div><p>合计 ${money(paid.reduce((s,x)=>s+x.amount_fen,0))}</p></article><article class="quota-summary-card"><div><span>待支付</span><strong>${items.filter(x=>x.status==='pending').length}</strong></div><p>超时后自动关闭本地订单</p></article></div><div class="toolbar"><div class="chips">${[['','全部'],['pending','待支付'],['paid','已支付'],['closed','已关闭'],['failed','失败']].map(([v,t])=>`<button class="chip ${status===v?'active':''}" data-status="${v}">${t}</button>`).join('')}</div></div><div class="card">${items.length?`<table class="table"><thead><tr><th>订单号 / 用户</th><th>额度</th><th>金额</th><th>状态</th><th>微信交易号</th><th>创建/支付时间</th></tr></thead><tbody>${items.map(x=>{const [label,color]=labels[x.status]||[x.status,''];return `<tr><td><strong>${esc(x.order_no)}</strong><br><small>${esc(x.username||x.user_id)}</small></td><td>${x.credit_count} 次</td><td>${money(x.amount_fen)}</td><td><span class="badge ${color}">${label}</span></td><td class="code">${esc(x.provider_transaction_id||'—')}</td><td>${fmtDate(x.created_at)}${x.paid_at?`<br><small>支付 ${fmtDate(x.paid_at)}</small>`:''}</td></tr>`}).join('')}</tbody></table>`:empty('暂无支付订单')}</div>`;document.querySelectorAll('[data-status]').forEach(b=>b.addEventListener('click',()=>{currentStatus=b.dataset.status;renderPaymentOrders()}))}
